name: Generate Snake

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Generate snake animation
      uses: Platane/snk@v2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        output: dist/github-snake.svg
    - name: Add & Commit
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add -A
        git commit -m "Generate snake animation"
    - name: Push Changes
      run: git push
